<?php
/**
 * This file is part of Docalist Data.
 *
 * Copyright (C) 2012-2018 Daniel Ménard
 *
 * For copyright and license information, please view the
 * LICENSE.txt file that was distributed with this source code.
 */
namespace Docalist\Data\Scripts\PostalAddressFormat;

/*
 * WARNING: This file has been generated by the script create-postal-address-formats.php
 * Do not modify this file directly!
 *
 * Generation date: 2018/01/17.
 *
 * Disable PHP_CodeSniffer warnings for lines which exceed the limit (e.g. the 'GB' entry)
 * phpcs:disable Generic.Files.LineLength.TooLong
 */

return [
    'AC' => [
        'zipex' => 'ASCN 1ZZ',
        'zip' => 'ASCN 1ZZ',
        'fmt' => '%N%n%O%n%A%n%C%n%Z'
    ],
    'AD' => [
        'zipex' => 'AD100,AD501,AD700',
        'zip' => 'AD[1-7]0\\d',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'AE' => [
        'fmt' => '%N%n%O%n%A%n%S',
        'state_name_type' => 'emirate',
        'require' => 'AS'
    ],
    'AF' => [
        'zipex' => '1001,2601,3801',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%C%n%Z'
    ],
    'AG' => [
        'require' => 'A'
    ],
    'AI' => [
        'zipex' => '2640',
        'zip' => '(?:AI-)?2640',
        'fmt' => '%N%n%O%n%A%n%C%n%Z'
    ],
    'AL' => [
        'zipex' => '1001,1017,3501',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z%n%C'
    ],
    'AM' => [
        'zipex' => '375010,0002,0010',
        'zip' => '(?:37)?\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z%n%C%n%S'
    ],
    'AO' => [

    ],
    'AQ' => [

    ],
    'AR' => [
        'upper' => 'ACZ',
        'zipex' => 'C1070AAM,C1000WAM,B1000TBU,X5187XAB',
        'zip' => '((?:[A-HJ-NP-Z])?\\d{4})([A-Z]{3})?',
        'fmt' => '%N%n%O%n%A%n%Z %C%n%S'
    ],
    'AS' => [
        'upper' => 'ACNOS',
        'require' => 'ACSZ',
        'zipex' => '96799',
        'zip' => '(96799)(?:[ \\-](\\d{4}))?',
        'zip_name_type' => 'zip',
        'fmt' => '%N%n%O%n%A%n%C %S %Z',
        'state_name_type' => 'state'
    ],
    'AT' => [
        'zipex' => '1010,3741',
        'zip' => '\\d{4}',
        'fmt' => '%O%n%N%n%A%n%Z %C',
        'require' => 'ACZ'
    ],
    'AU' => [
        'upper' => 'CS',
        'zipex' => '2060,3171,6430,4000,4006,3001',
        'zip' => '\\d{4}',
        'fmt' => '%O%n%N%n%A%n%C %S %Z',
        'state_name_type' => 'state',
        'locality_name_type' => 'suburb',
        'require' => 'ACSZ'
    ],
    'AW' => [

    ],
    'AX' => [
        'zipex' => '22150,22550,22240,22710,22270,22730,22430',
        'zip' => '22\\d{3}',
        'fmt' => '%O%n%N%n%A%nAX-%Z %C%nÅLAND',
        'require' => 'ACZ'
    ],
    'AZ' => [
        'zipex' => '1000',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%nAZ %Z %C'
    ],
    'BA' => [
        'zipex' => '71000',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'BB' => [
        'zipex' => 'BB23026,BB22025',
        'zip' => 'BB\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C, %S %Z',
        'state_name_type' => 'parish'
    ],
    'BD' => [
        'zipex' => '1340,1000',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%C - %Z'
    ],
    'BE' => [
        'zipex' => '4000,1000',
        'zip' => '\\d{4}',
        'fmt' => '%O%n%N%n%A%n%Z %C',
        'require' => 'ACZ'
    ],
    'BF' => [
        'fmt' => '%N%n%O%n%A%n%C %X'
    ],
    'BG' => [
        'zipex' => '1000,1700',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'BH' => [
        'zipex' => '317',
        'zip' => '(?:\\d|1[0-2])\\d{2}',
        'fmt' => '%N%n%O%n%A%n%C %Z'
    ],
    'BI' => [

    ],
    'BJ' => [
        'upper' => 'AC'
    ],
    'BL' => [
        'upper' => 'ACX',
        'zipex' => '97100',
        'zip' => '9[78][01]\\d{2}',
        'fmt' => '%O%n%N%n%A%n%Z %C %X',
        'require' => 'ACZ'
    ],
    'BM' => [
        'zipex' => 'FL 07,HM GX,HM 12',
        'zip' => '[A-Z]{2} ?[A-Z0-9]{2}',
        'fmt' => '%N%n%O%n%A%n%C %Z'
    ],
    'BN' => [
        'zipex' => 'BT2328,KA1131,BA1511',
        'zip' => '[A-Z]{2} ?\\d{4}',
        'fmt' => '%N%n%O%n%A%n%C %Z'
    ],
    'BO' => [
        'upper' => 'AC'
    ],
    'BQ' => [

    ],
    'BR' => [
        'upper' => 'CS',
        'zipex' => '40301-110,70002-900',
        'zip' => '\\d{5}-?\\d{3}',
        'sublocality_name_type' => 'neighborhood',
        'fmt' => '%O%n%N%n%A%n%D%n%C-%S%n%Z',
        'state_name_type' => 'state',
        'require' => 'ASCZ'
    ],
    'BS' => [
        'fmt' => '%N%n%O%n%A%n%C, %S',
        'state_name_type' => 'island'
    ],
    'BT' => [
        'zipex' => '11001,31101,35003',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C %Z'
    ],
    'BV' => [

    ],
    'BW' => [

    ],
    'BY' => [
        'zipex' => '223016,225860,220050',
        'zip' => '\\d{6}',
        'fmt' => '%S%n%Z %C%n%A%n%O%n%N'
    ],
    'BZ' => [

    ],
    'CA' => [
        'upper' => 'ACNOSZ',
        'zipex' => 'H3Z 2Y7,V8X 3X4,T0L 1K0,T0H 1A0,K1A 0B1',
        'zip' => '[ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJ-NPRSTV-Z] ?\\d[ABCEGHJ-NPRSTV-Z]\\d',
        'fmt' => '%N%n%O%n%A%n%C %S %Z',
        'require' => 'ACSZ'
    ],
    'CC' => [
        'upper' => 'CS',
        'zipex' => '6799',
        'zip' => '6799',
        'fmt' => '%O%n%N%n%A%n%C %S %Z'
    ],
    'CD' => [

    ],
    'CF' => [

    ],
    'CG' => [

    ],
    'CH' => [
        'upper' => '',
        'zipex' => '2544,1211,1556,3030',
        'zip' => '\\d{4}',
        'fmt' => '%O%n%N%n%A%nCH-%Z %C',
        'require' => 'ACZ'
    ],
    'CI' => [
        'fmt' => '%N%n%O%n%X %A %C %X'
    ],
    'CK' => [

    ],
    'CL' => [
        'zipex' => '8340457,8720019,1230000,8329100',
        'zip' => '\\d{7}',
        'fmt' => '%N%n%O%n%A%n%Z %C%n%S'
    ],
    'CM' => [

    ],
    'CN' => [
        'upper' => 'S',
        'zipex' => '266033,317204,100096,100808',
        'zip' => '\\d{6}',
        'sublocality_name_type' => 'district',
        'fmt' => '%Z%n%S%C%D%n%A%n%O%n%N',
        'require' => 'ACSZ'
    ],
    'CO' => [
        'require' => 'AS',
        'zipex' => '111221,130001,760011',
        'zip' => '\\d{6}',
        'fmt' => '%N%n%O%n%A%n%C, %S, %Z',
        'state_name_type' => 'department'
    ],
    'CR' => [
        'zipex' => '1000,2010,1001',
        'zip' => '\\d{4,5}|\\d{3}-\\d{4}',
        'fmt' => '%N%n%O%n%A%n%S, %C%n%Z',
        'require' => 'ACS'
    ],
    'CV' => [
        'zipex' => '7600',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C%n%S',
        'state_name_type' => 'island'
    ],
    'CW' => [

    ],
    'CX' => [
        'upper' => 'CS',
        'zipex' => '6798',
        'zip' => '6798',
        'fmt' => '%O%n%N%n%A%n%C %S %Z'
    ],
    'CY' => [
        'zipex' => '2008,3304,1900',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'CZ' => [
        'zipex' => '100 00,251 66,530 87,110 00,225 99',
        'zip' => '\\d{3} ?\\d{2}',
        'fmt' => '%N%n%O%n%A%n%Z %C',
        'require' => 'ACZ'
    ],
    'DE' => [
        'zipex' => '26133,53225',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C',
        'require' => 'ACZ'
    ],
    'DJ' => [

    ],
    'DK' => [
        'zipex' => '8660,1566',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C',
        'require' => 'ACZ'
    ],
    'DM' => [

    ],
    'DO' => [
        'zipex' => '11903,10101',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'DZ' => [
        'zipex' => '40304,16027',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'EC' => [
        'upper' => 'CZ',
        'zipex' => '090105,092301',
        'zip' => '\\d{6}',
        'fmt' => '%N%n%O%n%A%n%Z%n%C'
    ],
    'EE' => [
        'zipex' => '69501,11212',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C %S',
        'require' => 'ACZ',
        'state_name_type' => 'county'
    ],
    'EG' => [
        'zipex' => '12411,11599',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C%n%S%n%Z'
    ],
    'EH' => [
        'zipex' => '70000,72000',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'ER' => [

    ],
    'ES' => [
        'upper' => 'CS',
        'zipex' => '28039,28300,28070',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C %S',
        'require' => 'ACSZ'
    ],
    'ET' => [
        'zipex' => '1000',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'FI' => [
        'zipex' => '00550,00011',
        'zip' => '\\d{5}',
        'fmt' => '%O%n%N%n%A%nFI-%Z %C',
        'require' => 'ACZ'
    ],
    'FJ' => [

    ],
    'FK' => [
        'upper' => 'CZ',
        'zipex' => 'FIQQ 1ZZ',
        'zip' => 'FIQQ 1ZZ',
        'fmt' => '%N%n%O%n%A%n%C%n%Z',
        'require' => 'ACZ'
    ],
    'FM' => [
        'upper' => 'ACNOS',
        'require' => 'ACSZ',
        'zipex' => '96941,96944',
        'zip' => '(9694[1-4])(?:[ \\-](\\d{4}))?',
        'zip_name_type' => 'zip',
        'fmt' => '%N%n%O%n%A%n%C %S %Z',
        'state_name_type' => 'state'
    ],
    'FO' => [
        'zipex' => '100',
        'zip' => '\\d{3}',
        'fmt' => '%N%n%O%n%A%nFO%Z %C'
    ],
    'FR' => [
        'upper' => 'CX',
        'zipex' => '33380,34092,33506',
        'zip' => '\\d{2} ?\\d{3}',
        'fmt' => '%O%n%N%n%A%n%Z %C %X',
        'require' => 'ACZ'
    ],
    'GA' => [

    ],
    'GB' => [
        'upper' => 'CZ',
        'zipex' => 'EC1Y 8SY,GIR 0AA,M2 5BQ,M34 4AB,CR0 2YR,DN16 9AA,W1A 4ZZ,EC1A 1HQ,OX14 4PG,BS18 8HF,NR25 7HG,RH6 0NP,BH23 6AA,B6 5BA,SO23 9AP,PO1 3AX,BFPO 61',
        'zip' => 'GIR ?0AA|(?:(?:AB|AL|B|BA|BB|BD|BF|BH|BL|BN|BR|BS|BT|BX|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(?:\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}))|BFPO ?\\d{1,4}',
        'fmt' => '%N%n%O%n%A%n%C%n%Z',
        'require' => 'ACZ',
        'locality_name_type' => 'post_town'
    ],
    'GD' => [

    ],
    'GE' => [
        'zipex' => '0101',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'GF' => [
        'upper' => 'ACX',
        'zipex' => '97300',
        'zip' => '9[78]3\\d{2}',
        'fmt' => '%O%n%N%n%A%n%Z %C %X',
        'require' => 'ACZ'
    ],
    'GG' => [
        'upper' => 'CZ',
        'zipex' => 'GY1 1AA,GY2 2BT',
        'zip' => 'GY\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}',
        'fmt' => '%N%n%O%n%A%n%C%nGUERNSEY%n%Z',
        'require' => 'ACZ'
    ],
    'GH' => [

    ],
    'GI' => [
        'zipex' => 'GX11 1AA',
        'zip' => 'GX11 1AA',
        'fmt' => '%N%n%O%n%A%nGIBRALTAR%n%Z',
        'require' => 'A'
    ],
    'GL' => [
        'zipex' => '3900,3950,3911',
        'zip' => '39\\d{2}',
        'fmt' => '%N%n%O%n%A%n%Z %C',
        'require' => 'ACZ'
    ],
    'GM' => [

    ],
    'GN' => [
        'zipex' => '001,200,100',
        'zip' => '\\d{3}',
        'fmt' => '%N%n%O%n%Z %A %C'
    ],
    'GP' => [
        'upper' => 'ACX',
        'zipex' => '97100',
        'zip' => '9[78][01]\\d{2}',
        'fmt' => '%O%n%N%n%A%n%Z %C %X',
        'require' => 'ACZ'
    ],
    'GQ' => [

    ],
    'GR' => [
        'zipex' => '151 24,151 10,101 88',
        'zip' => '\\d{3} ?\\d{2}',
        'fmt' => '%N%n%O%n%A%n%Z %C',
        'require' => 'ACZ'
    ],
    'GS' => [
        'upper' => 'CZ',
        'zipex' => 'SIQQ 1ZZ',
        'zip' => 'SIQQ 1ZZ',
        'fmt' => '%N%n%O%n%A%n%n%C%n%Z',
        'require' => 'ACZ'
    ],
    'GT' => [
        'zipex' => '09001,01501',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z- %C'
    ],
    'GU' => [
        'upper' => 'ACNO',
        'zipex' => '96910,96931',
        'zip' => '(969(?:[12]\\d|3[12]))(?:[ \\-](\\d{4}))?',
        'zip_name_type' => 'zip',
        'fmt' => '%N%n%O%n%A%n%C %Z',
        'require' => 'ACZ'
    ],
    'GW' => [
        'zipex' => '1000,1011',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'GY' => [

    ],
    'HK' => [
        'upper' => 'S',
        'fmt' => '%S%n%C%n%A%n%O%n%N',
        'state_name_type' => 'area',
        'locality_name_type' => 'district',
        'require' => 'AS'
    ],
    'HM' => [
        'upper' => 'CS',
        'zipex' => '7050',
        'zip' => '\\d{4}',
        'fmt' => '%O%n%N%n%A%n%C %S %Z'
    ],
    'HN' => [
        'zipex' => '31301',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C, %S%n%Z',
        'require' => 'ACS'
    ],
    'HR' => [
        'zipex' => '10000,21001,10002',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%nHR-%Z %C'
    ],
    'HT' => [
        'zipex' => '6120,5310,6110,8510',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%nHT%Z %C'
    ],
    'HU' => [
        'upper' => 'ACNO',
        'zipex' => '1037,2380,1540',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%C%n%A%n%Z',
        'require' => 'ACZ'
    ],
    'ID' => [
        'zipex' => '40115',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C%n%S %Z',
        'require' => 'AS'
    ],
    'IE' => [
        'sublocality_name_type' => 'townland',
        'zipex' => 'A65 F4E2',
        'zip' => '[\\dA-Z]{3} ?[\\dA-Z]{4}',
        'zip_name_type' => 'eircode',
        'fmt' => '%N%n%O%n%A%n%D%n%C%n%S %Z',
        'state_name_type' => 'county'
    ],
    'IL' => [
        'zipex' => '9614303',
        'zip' => '\\d{5}(?:\\d{2})?',
        'fmt' => '%N%n%O%n%A%n%C %Z'
    ],
    'IM' => [
        'upper' => 'CZ',
        'zipex' => 'IM2 1AA,IM99 1PS',
        'zip' => 'IM\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}',
        'fmt' => '%N%n%O%n%A%n%C%n%Z',
        'require' => 'ACZ'
    ],
    'IN' => [
        'zipex' => '110034,110001',
        'zip' => '\\d{6}',
        'zip_name_type' => 'pin',
        'fmt' => '%N%n%O%n%A%n%C %Z%n%S',
        'state_name_type' => 'state',
        'require' => 'ACSZ'
    ],
    'IO' => [
        'upper' => 'CZ',
        'zipex' => 'BBND 1ZZ',
        'zip' => 'BBND 1ZZ',
        'fmt' => '%N%n%O%n%A%n%C%n%Z',
        'require' => 'ACZ'
    ],
    'IQ' => [
        'upper' => 'CS',
        'zipex' => '31001',
        'zip' => '\\d{5}',
        'fmt' => '%O%n%N%n%A%n%C, %S%n%Z',
        'require' => 'ACS'
    ],
    'IR' => [
        'sublocality_name_type' => 'neighborhood',
        'zipex' => '11936-12345',
        'zip' => '\\d{5}-?\\d{5}',
        'fmt' => '%O%n%N%n%S%n%C, %D%n%A%n%Z'
    ],
    'IS' => [
        'zipex' => '320,121,220,110',
        'zip' => '\\d{3}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'IT' => [
        'upper' => 'CS',
        'zipex' => '00144,47037,39049',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C %S',
        'require' => 'ACSZ'
    ],
    'JE' => [
        'upper' => 'CZ',
        'zipex' => 'JE1 1AA,JE2 2BT',
        'zip' => 'JE\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}',
        'fmt' => '%N%n%O%n%A%n%C%nJERSEY%n%Z',
        'require' => 'ACZ'
    ],
    'JM' => [
        'fmt' => '%N%n%O%n%A%n%C%n%S %X',
        'state_name_type' => 'parish',
        'require' => 'ACS'
    ],
    'JO' => [
        'zipex' => '11937,11190',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C %Z'
    ],
    'JP' => [
        'upper' => 'S',
        'zipex' => '154-0023,350-1106,951-8073,112-0001,208-0032,231-0012',
        'zip' => '\\d{3}-?\\d{4}',
        'fmt' => '〒%Z%n%S%C%n%A%n%O%n%N',
        'state_name_type' => 'prefecture',
        'require' => 'ACSZ'
    ],
    'KE' => [
        'zipex' => '20100,00100',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C%n%Z'
    ],
    'KG' => [
        'zipex' => '720001',
        'zip' => '\\d{6}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'KH' => [
        'zipex' => '12203,14206,12000',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C %Z'
    ],
    'KI' => [
        'upper' => 'ACNOS',
        'fmt' => '%N%n%O%n%A%n%S%n%C',
        'state_name_type' => 'island'
    ],
    'KM' => [
        'upper' => 'AC'
    ],
    'KN' => [
        'fmt' => '%N%n%O%n%A%n%C, %S',
        'state_name_type' => 'island',
        'require' => 'ACS'
    ],
    'KR' => [
        'upper' => 'Z',
        'zipex' => '03051',
        'zip' => '\\d{5}',
        'sublocality_name_type' => 'district',
        'fmt' => '%S %C%D%n%A%n%O%n%N%n%Z',
        'require' => 'ACSZ',
        'state_name_type' => 'do_si'
    ],
    'KW' => [
        'zipex' => '54541,54551,54404,13009',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'KY' => [
        'zipex' => 'KY1-1100,KY1-1702,KY2-2101',
        'zip' => 'KY\\d-\\d{4}',
        'fmt' => '%N%n%O%n%A%n%S %Z',
        'state_name_type' => 'island',
        'require' => 'AS'
    ],
    'KZ' => [
        'zipex' => '040900,050012',
        'zip' => '\\d{6}',
        'fmt' => '%Z%n%S%n%C%n%A%n%O%n%N'
    ],
    'LA' => [
        'zipex' => '01160,01000',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'LB' => [
        'zipex' => '2038 3054,1107 2810,1000',
        'zip' => '(?:\\d{4})(?: ?(?:\\d{4}))?',
        'fmt' => '%N%n%O%n%A%n%C %Z'
    ],
    'LC' => [

    ],
    'LI' => [
        'zipex' => '9496,9491,9490,9485',
        'zip' => '948[5-9]|949[0-8]',
        'fmt' => '%O%n%N%n%A%nFL-%Z %C',
        'require' => 'ACZ'
    ],
    'LK' => [
        'zipex' => '20000,00100',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C%n%Z'
    ],
    'LR' => [
        'zipex' => '1000',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'LS' => [
        'zipex' => '100',
        'zip' => '\\d{3}',
        'fmt' => '%N%n%O%n%A%n%C %Z'
    ],
    'LT' => [
        'zipex' => '04340,03500',
        'zip' => '\\d{5}',
        'fmt' => '%O%n%N%n%A%nLT-%Z %C %S',
        'require' => 'ACZ',
        'state_name_type' => 'county'
    ],
    'LU' => [
        'zipex' => '4750,2998',
        'zip' => '\\d{4}',
        'fmt' => '%O%n%N%n%A%nL-%Z %C',
        'require' => 'ACZ'
    ],
    'LV' => [
        'zipex' => 'LV-1073,LV-1000',
        'zip' => 'LV-\\d{4}',
        'fmt' => '%N%n%O%n%A%n%C, %Z',
        'require' => 'ACZ'
    ],
    'LY' => [

    ],
    'MA' => [
        'zipex' => '53000,10000,20050,16052',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'MC' => [
        'zipex' => '98000,98020,98011,98001',
        'zip' => '980\\d{2}',
        'fmt' => '%N%n%O%n%A%nMC-%Z %C %X'
    ],
    'MD' => [
        'zipex' => '2012,2019',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%nMD-%Z %C'
    ],
    'ME' => [
        'zipex' => '81257,81258,81217,84314,85366',
        'zip' => '8\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'MF' => [
        'upper' => 'ACX',
        'zipex' => '97100',
        'zip' => '9[78][01]\\d{2}',
        'fmt' => '%O%n%N%n%A%n%Z %C %X',
        'require' => 'ACZ'
    ],
    'MG' => [
        'zipex' => '501,101',
        'zip' => '\\d{3}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'MH' => [
        'upper' => 'ACNOS',
        'require' => 'ACSZ',
        'zipex' => '96960,96970',
        'zip' => '(969[67]\\d)(?:[ \\-](\\d{4}))?',
        'zip_name_type' => 'zip',
        'fmt' => '%N%n%O%n%A%n%C %S %Z',
        'state_name_type' => 'state'
    ],
    'MK' => [
        'zipex' => '1314,1321,1443,1062',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'ML' => [

    ],
    'MM' => [
        'zipex' => '11181',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C, %Z'
    ],
    'MN' => [
        'zipex' => '65030,65270',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C%n%S %Z'
    ],
    'MO' => [
        'fmt' => '%A%n%O%n%N',
        'require' => 'A'
    ],
    'MP' => [
        'upper' => 'ACNOS',
        'require' => 'ACSZ',
        'zipex' => '96950,96951,96952',
        'zip' => '(9695[012])(?:[ \\-](\\d{4}))?',
        'zip_name_type' => 'zip',
        'fmt' => '%N%n%O%n%A%n%C %S %Z',
        'state_name_type' => 'state'
    ],
    'MQ' => [
        'upper' => 'ACX',
        'zipex' => '97220',
        'zip' => '9[78]2\\d{2}',
        'fmt' => '%O%n%N%n%A%n%Z %C %X',
        'require' => 'ACZ'
    ],
    'MR' => [
        'upper' => 'AC'
    ],
    'MS' => [

    ],
    'MT' => [
        'upper' => 'CZ',
        'zipex' => 'NXR 01,ZTN 05,GPO 01,BZN 1130,SPB 6031,VCT 1753',
        'zip' => '[A-Z]{3} ?\\d{2,4}',
        'fmt' => '%N%n%O%n%A%n%C %Z'
    ],
    'MU' => [
        'upper' => 'CZ',
        'zipex' => '42602',
        'zip' => '\\d{3}(?:\\d{2}|[A-Z]{2}\\d{3})',
        'fmt' => '%N%n%O%n%A%n%Z%n%C'
    ],
    'MV' => [
        'zipex' => '20026',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C %Z'
    ],
    'MW' => [
        'fmt' => '%N%n%O%n%A%n%C %X'
    ],
    'MX' => [
        'upper' => 'CSZ',
        'zipex' => '02860,77520,06082',
        'zip' => '\\d{5}',
        'sublocality_name_type' => 'neighborhood',
        'fmt' => '%N%n%O%n%A%n%D%n%Z %C, %S',
        'state_name_type' => 'state',
        'require' => 'ACZ'
    ],
    'MY' => [
        'upper' => 'CS',
        'zipex' => '43000,50754,88990,50670',
        'zip' => '\\d{5}',
        'sublocality_name_type' => 'village_township',
        'fmt' => '%N%n%O%n%A%n%D%n%Z %C%n%S',
        'require' => 'ACZ',
        'state_name_type' => 'state'
    ],
    'MZ' => [
        'zipex' => '1102,1119,3212',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'NA' => [

    ],
    'NC' => [
        'upper' => 'ACX',
        'zipex' => '98814,98800,98810',
        'zip' => '988\\d{2}',
        'fmt' => '%O%n%N%n%A%n%Z %C %X',
        'require' => 'ACZ'
    ],
    'NE' => [
        'zipex' => '8001',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'NF' => [
        'upper' => 'CS',
        'zipex' => '2899',
        'zip' => '2899',
        'fmt' => '%O%n%N%n%A%n%C %S %Z'
    ],
    'NG' => [
        'upper' => 'CS',
        'zipex' => '930283,300001,931104',
        'zip' => '\\d{6}',
        'fmt' => '%N%n%O%n%A%n%D%n%C %Z%n%S',
        'state_name_type' => 'state'
    ],
    'NI' => [
        'upper' => 'CS',
        'zipex' => '52000',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z%n%C, %S',
        'state_name_type' => 'department'
    ],
    'NL' => [
        'zipex' => '1234 AB,2490 AA',
        'zip' => '\\d{4} ?[A-Z]{2}',
        'fmt' => '%O%n%N%n%A%n%Z %C',
        'require' => 'ACZ'
    ],
    'NO' => [
        'zipex' => '0025,0107,6631',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C',
        'require' => 'ACZ',
        'locality_name_type' => 'post_town'
    ],
    'NP' => [
        'zipex' => '44601',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C %Z'
    ],
    'NR' => [
        'fmt' => '%N%n%O%n%A%n%S',
        'state_name_type' => 'district',
        'require' => 'AS'
    ],
    'NU' => [

    ],
    'NZ' => [
        'zipex' => '6001,6015,6332,8252,1030',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%D%n%C %Z',
        'require' => 'ACZ'
    ],
    'OM' => [
        'zipex' => '133,112,111',
        'zip' => '(?:PC )?\\d{3}',
        'fmt' => '%N%n%O%n%A%n%Z%n%C'
    ],
    'PA' => [
        'upper' => 'CS',
        'fmt' => '%N%n%O%n%A%n%C%n%S'
    ],
    'PE' => [
        'zipex' => 'LIMA 23,LIMA 42,CALLAO 2,02001',
        'zip' => '(?:LIMA \\d{1,2}|CALLAO 0?\\d)|[0-2]\\d{4}',
        'fmt' => '%N%n%O%n%A%n%C %Z%n%S'
    ],
    'PF' => [
        'upper' => 'CS',
        'zipex' => '98709',
        'zip' => '987\\d{2}',
        'fmt' => '%N%n%O%n%A%n%Z %C %S',
        'state_name_type' => 'island',
        'require' => 'ACSZ'
    ],
    'PG' => [
        'zipex' => '111',
        'zip' => '\\d{3}',
        'fmt' => '%N%n%O%n%A%n%C %Z %S',
        'require' => 'ACS'
    ],
    'PH' => [
        'zipex' => '1008,1050,1135,1207,2000,1000',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%D, %C%n%Z %S'
    ],
    'PK' => [
        'zipex' => '44000',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C-%Z'
    ],
    'PL' => [
        'zipex' => '00-950,05-470,48-300,32-015,00-940',
        'zip' => '\\d{2}-\\d{3}',
        'fmt' => '%N%n%O%n%A%n%Z %C',
        'require' => 'ACZ'
    ],
    'PM' => [
        'upper' => 'ACX',
        'zipex' => '97500',
        'zip' => '9[78]5\\d{2}',
        'fmt' => '%O%n%N%n%A%n%Z %C %X',
        'require' => 'ACZ'
    ],
    'PN' => [
        'upper' => 'CZ',
        'zipex' => 'PCRN 1ZZ',
        'zip' => 'PCRN 1ZZ',
        'fmt' => '%N%n%O%n%A%n%C%n%Z',
        'require' => 'ACZ'
    ],
    'PR' => [
        'upper' => 'ACNO',
        'zipex' => '00930',
        'zip' => '(00[679]\\d{2})(?:[ \\-](\\d{4}))?',
        'zip_name_type' => 'zip',
        'fmt' => '%N%n%O%n%A%n%C PR %Z',
        'require' => 'ACZ'
    ],
    'PS' => [

    ],
    'PT' => [
        'zipex' => '2725-079,1250-096,1201-950,2860-571,1208-148',
        'zip' => '\\d{4}-\\d{3}',
        'fmt' => '%N%n%O%n%A%n%Z %C',
        'require' => 'ACZ'
    ],
    'PW' => [
        'upper' => 'ACNOS',
        'require' => 'ACSZ',
        'zipex' => '96940',
        'zip' => '(969(?:39|40))(?:[ \\-](\\d{4}))?',
        'zip_name_type' => 'zip',
        'fmt' => '%N%n%O%n%A%n%C %S %Z',
        'state_name_type' => 'state'
    ],
    'PY' => [
        'zipex' => '1536,1538,1209',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'QA' => [
        'upper' => 'AC'
    ],
    'RE' => [
        'upper' => 'ACX',
        'zipex' => '97400',
        'zip' => '9[78]4\\d{2}',
        'fmt' => '%O%n%N%n%A%n%Z %C %X',
        'require' => 'ACZ'
    ],
    'RO' => [
        'upper' => 'AC',
        'zipex' => '060274,061357,200716',
        'zip' => '\\d{6}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'RS' => [
        'zipex' => '106314',
        'zip' => '\\d{5,6}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'RU' => [
        'upper' => 'AC',
        'zipex' => '247112,103375,188300',
        'zip' => '\\d{6}',
        'fmt' => '%N%n%O%n%A%n%C%n%S%n%Z',
        'state_name_type' => 'oblast',
        'require' => 'ACSZ'
    ],
    'RW' => [
        'upper' => 'AC'
    ],
    'SA' => [
        'zipex' => '11564,11187,11142',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C %Z'
    ],
    'SB' => [

    ],
    'SC' => [
        'upper' => 'S',
        'fmt' => '%N%n%O%n%A%n%C%n%S',
        'state_name_type' => 'island'
    ],
    'SE' => [
        'zipex' => '11455,12345,10500',
        'zip' => '\\d{3} ?\\d{2}',
        'fmt' => '%O%n%N%n%A%nSE-%Z %C',
        'require' => 'ACZ',
        'locality_name_type' => 'post_town'
    ],
    'SG' => [
        'zipex' => '546080,308125,408600',
        'zip' => '\\d{6}',
        'fmt' => '%N%n%O%n%A%nSINGAPORE %Z',
        'require' => 'AZ'
    ],
    'SH' => [
        'upper' => 'CZ',
        'zipex' => 'STHL 1ZZ',
        'zip' => '(?:ASCN|STHL) 1ZZ',
        'fmt' => '%N%n%O%n%A%n%C%n%Z',
        'require' => 'ACZ'
    ],
    'SI' => [
        'zipex' => '4000,1001,2500',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%nSI- %Z %C'
    ],
    'SJ' => [
        'zipex' => '9170',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C',
        'require' => 'ACZ',
        'locality_name_type' => 'post_town'
    ],
    'SK' => [
        'zipex' => '010 01,023 14,972 48,921 01,975 99',
        'zip' => '\\d{3} ?\\d{2}',
        'fmt' => '%N%n%O%n%A%n%Z %C',
        'require' => 'ACZ'
    ],
    'SL' => [

    ],
    'SM' => [
        'zipex' => '47890,47891,47895,47899',
        'zip' => '4789\\d',
        'fmt' => '%N%n%O%n%A%n%Z %C',
        'require' => 'AZ'
    ],
    'SN' => [
        'zipex' => '12500,46024,16556,10000',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'SO' => [
        'upper' => 'ACS',
        'zipex' => 'JH 09010,AD 11010',
        'zip' => '[A-Z]{2} ?\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C, %S %Z',
        'require' => 'ACS'
    ],
    'SR' => [
        'upper' => 'AS',
        'fmt' => '%N%n%O%n%A%n%C%n%S'
    ],
    'SS' => [

    ],
    'ST' => [

    ],
    'SV' => [
        'upper' => 'CSZ',
        'zipex' => 'CP 1101',
        'zip' => 'CP [1-3][1-7][0-2]\\d',
        'fmt' => '%N%n%O%n%A%n%Z-%C%n%S',
        'require' => 'ACS'
    ],
    'SX' => [

    ],
    'SZ' => [
        'upper' => 'ACZ',
        'zipex' => 'H100',
        'zip' => '[HLMS]\\d{3}',
        'fmt' => '%N%n%O%n%A%n%C%n%Z'
    ],
    'TA' => [
        'zipex' => 'TDCU 1ZZ',
        'zip' => 'TDCU 1ZZ',
        'fmt' => '%N%n%O%n%A%n%C%n%Z'
    ],
    'TC' => [
        'upper' => 'CZ',
        'zipex' => 'TKCA 1ZZ',
        'zip' => 'TKCA 1ZZ',
        'fmt' => '%N%n%O%n%A%n%C%n%Z',
        'require' => 'ACZ'
    ],
    'TD' => [

    ],
    'TF' => [

    ],
    'TG' => [

    ],
    'TH' => [
        'upper' => 'S',
        'zipex' => '10150,10210',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%D %C%n%S %Z'
    ],
    'TJ' => [
        'zipex' => '735450,734025',
        'zip' => '\\d{6}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'TK' => [

    ],
    'TL' => [

    ],
    'TM' => [
        'zipex' => '744000',
        'zip' => '\\d{6}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'TN' => [
        'zipex' => '1002,8129,3100,1030',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'TO' => [

    ],
    'TR' => [
        'zipex' => '01960,06101',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C/%S',
        'require' => 'ACZ',
        'locality_name_type' => 'district'
    ],
    'TT' => [

    ],
    'TV' => [
        'upper' => 'ACS',
        'fmt' => '%N%n%O%n%A%n%C%n%S',
        'state_name_type' => 'island'
    ],
    'TW' => [
        'zipex' => '104,106,10603,40867',
        'zip' => '\\d{3}(?:\\d{2})?',
        'fmt' => '%Z%n%S%C%n%A%n%O%n%N',
        'require' => 'ACSZ',
        'state_name_type' => 'county'
    ],
    'TZ' => [
        'zipex' => '6090,34413',
        'zip' => '\\d{4,5}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'UA' => [
        'zipex' => '15432,01055,01001',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%C%n%S%n%Z',
        'require' => 'ACSZ',
        'state_name_type' => 'oblast'
    ],
    'UG' => [

    ],
    'UM' => [
        'upper' => 'ACNOS',
        'require' => 'ACS',
        'zipex' => '96898',
        'zip' => '96898',
        'zip_name_type' => 'zip',
        'fmt' => '%N%n%O%n%A%n%C %S %Z',
        'state_name_type' => 'state'
    ],
    'US' => [
        'upper' => 'CS',
        'zipex' => '95014,22162-1010',
        'zip' => '(\\d{5})(?:[ \\-](\\d{4}))?',
        'zip_name_type' => 'zip',
        'fmt' => '%N%n%O%n%A%n%C, %S %Z',
        'state_name_type' => 'state',
        'require' => 'ACSZ'
    ],
    'UY' => [
        'upper' => 'CS',
        'zipex' => '11600',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C %S'
    ],
    'UZ' => [
        'upper' => 'CS',
        'zipex' => '702100,700000',
        'zip' => '\\d{6}',
        'fmt' => '%N%n%O%n%A%n%Z %C%n%S'
    ],
    'VA' => [
        'zipex' => '00120',
        'zip' => '00120',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'VC' => [
        'zipex' => 'VC0100,VC0110,VC0400',
        'zip' => 'VC\\d{4}',
        'fmt' => '%N%n%O%n%A%n%C %Z'
    ],
    'VE' => [
        'upper' => 'CS',
        'zipex' => '1010,3001,8011,1020',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%C %Z, %S',
        'state_name_type' => 'state',
        'require' => 'ACS'
    ],
    'VG' => [
        'zipex' => 'VG1110,VG1150,VG1160',
        'zip' => 'VG\\d{4}',
        'fmt' => '%N%n%O%n%A%n%C%n%Z',
        'require' => 'A'
    ],
    'VI' => [
        'upper' => 'ACNOS',
        'require' => 'ACSZ',
        'zipex' => '00802-1222,00850-9802',
        'zip' => '(008(?:(?:[0-4]\\d)|(?:5[01])))(?:[ \\-](\\d{4}))?',
        'zip_name_type' => 'zip',
        'fmt' => '%N%n%O%n%A%n%C %S %Z',
        'state_name_type' => 'state'
    ],
    'VN' => [
        'zipex' => '119415,136065,720344',
        'zip' => '\\d{6}',
        'fmt' => '%N%n%O%n%A%n%C%n%S %Z'
    ],
    'VU' => [

    ],
    'WF' => [
        'upper' => 'ACX',
        'zipex' => '98600',
        'zip' => '986\\d{2}',
        'fmt' => '%O%n%N%n%A%n%Z %C %X',
        'require' => 'ACZ'
    ],
    'WS' => [

    ],
    'XK' => [
        'zipex' => '10000',
        'zip' => '[1-7]\\d{4}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'YE' => [

    ],
    'YT' => [
        'upper' => 'ACX',
        'zipex' => '97600',
        'zip' => '976\\d{2}',
        'fmt' => '%O%n%N%n%A%n%Z %C %X',
        'require' => 'ACZ'
    ],
    'ZA' => [
        'zipex' => '0083,1451,0001',
        'zip' => '\\d{4}',
        'fmt' => '%N%n%O%n%A%n%D%n%C%n%Z',
        'require' => 'ACZ'
    ],
    'ZM' => [
        'zipex' => '50100,50101',
        'zip' => '\\d{5}',
        'fmt' => '%N%n%O%n%A%n%Z %C'
    ],
    'ZW' => [

    ],
    'ZZ' => [
        'upper' => 'C',
        'sublocality_name_type' => 'suburb',
        'zip_name_type' => 'postal',
        'fmt' => '%O%n%N%n%A%n%D%n%Z %C %X%n%S',
        'state_name_type' => 'province',
        'locality_name_type' => 'city',
        'require' => 'AC'
    ]
];
